---
title: "test"
author: "Souilla Luc"
date: "2025-07-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(dplyr)
library(ggplot2)

file_path<-"/Users/souilla/Documents/Documents/GitHub/BodyCap_Trec/data/Visite1NeutrteP004_TREC.csv"
  df <- fread(file_path, skip = 5, encoding = "Latin-1", fill = TRUE)
  df<-df[,1:5]
```

```{r}
# Définition des périodes avec heures début/fin
periods <- data.frame(
  period = c("Baseline", "Exercise", "Cooldown"),
  start = c("08:09:55", "08:30:55", "09:00:00"),
  end = c("08:19:55", "08:45:00", "10:20:00"),
  stringsAsFactors = FALSE
)

```

``` {r}
# Fonction de traitement
process_data <- function(df, start_time, end_time) {
  names(df) <- tolower(trimws(names(df)))
  print(names(df))
  # Détection des colonnes
  time_col <- "hour"
  temp_col <- "temperature (°c)"

  # Vérification que les colonnes existent
  if (!(time_col %in% names(df)) || !(temp_col %in% names(df))) {
    stop("❌ La colonne 'Hour' ou 'Temperature (°C)' est introuvable.")
  }
  
  df$time_parsed <- as.POSIXct(df[[time_col]], format = "%H:%M:%S", tz = "UTC")
  df$temperature <- as.numeric(df[[temp_col]])
  
  start <- as.POSIXct(start_time, format = "%H:%M:%S", tz = "UTC")
  end <- as.POSIXct(end_time, format = "%H:%M:%S", tz = "UTC")
  
  df_period <- df %>% filter(time_parsed >= start & time_parsed <= end)
  
  mean_temp <- mean(df_period$temperature, na.rm = TRUE)
  sd_temp <- sd(df_period$temperature, na.rm = TRUE)
  n_temp <- sum(!is.na(df_period$temperature))
  
  data.frame(
    start = start_time,
    end = end_time,
    mean = mean_temp,
    sd = sd_temp,
    n = n_temp
  )
}

# Appliquer la fonction à chaque période
results <- do.call(rbind, lapply(1:nrow(periods), function(i) {
  res <- process_data(df, periods$start[i], periods$end[i])
  res$period <- periods$period[i]
  return(res)
}))

print(results)

```

```{r}
df$periods<-NA
for (i in 1:nrow(periods)) {
  df$periods[df$Hour >= periods$start[i] & df$Hour <= periods$end[i]] <- periods$period[i]
}

df$Hour <- as.POSIXct(df$Hour, format = "%H:%M:%S")
```

```{r}
df <- df %>% filter(!is.na(Period))

plot<- ggplot(df, aes(Hour, `Temperature (°C)`, color= periods, group= periods)) +
               geom_line(size=1)+
   scale_x_datetime(date_breaks = "30 min", date_labels = "%H:%M") +
  labs(title = "Temperature plot", x = "Hour", y = "Temperature (°C)") +
  theme_minimal()

plot
``` 





